### ISSUE TITLE
Implement all features from legacy VideoDb

### ISSUE THREAD

**Issue by viper3400** [viper3400/HomeWeb#28]
This is a list of functions need to gain full feature set of legacy video db.

# User Functions
- [x] mark / unmark a movie as favorite (user dependent) (#29)
- [x] mark / unmark a movie as to watch again (user dependent) (#30)
- [x] show favorite / to watch again in movie search results (user dependent)  (#34)

# Search functions (1)
- [x] get surprise videos
- [x] search movie by genre

_With complete user & search functions it should be possible to replace the legacy main page!_

# Search functions (2)
- [x] search movie by barcode (is this urgent?)
- [ ] search movie with a maximum runtime of x
- [ ] search movie by actor (is this urgent?)

# ViewGroup functions / seen list
- [x] list all seen movies (#21)
- [x] remove a seen date for a movie

# Admin functions
- [x] create a movie (from metadata)
- [x] delete (Soft delete) a movie
- [x] get free diskids
- [x] move a movie to other location
- [x] exchange location of two movies
- [ ] download missing cover pics
- [ ] sanity check for cover pics
- [ ] sanity check for diskids
